version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/pltr

    steps:
      - checkout
      - run:
          - name: Update npm
          - command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          - name: Install npm packages
          - command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      - run:
          - name: Build pltr
          - command: npm run build
      - run:
          - name: Setup git config
          - command: |
              git config user.name 'CircleCI'
              git config user.email 'ci-build@circle.ci'
      - add_ssh_keys:
          fingerprints:
            - "76:ff:9f:86:58:19:75:66:ff:13:eb:34:71:4a:62:d8"
      - run:
          - name: Deploy pltr
          - command: |
              git add dist/
              git commit --allow-empty -m "pltr deploy commit [skip ci]"
              git push -u origin master
