name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build extension
      run: make build

    - name: Create extension package
      run: make zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: dist/pltr.zip
        retention-days: 7

    - name: Upload dist directory
      uses: actions/upload-artifact@v4
      with:
        name: extension-dist
        path: dist/pltr/
        retention-days: 7

    - name: Get version from manifest
      if: github.ref == 'refs/heads/master'
      id: version
      run: |
        VERSION=$(jq -r .version manifest.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/pltr.zip
        asset_name: pltr-v${{ steps.version.outputs.version }}.zip
        asset_content_type: application/zip 